#! /bin/bash
#This is a comment
echo "Hello World"

echo Our Shell name is  $BASH
echo Our Shell Version is  $BASH_VERSION
echo Our Home Directory is $HOME
echo Our Current WD is $PWD

NAME=Karthik
Value=100

echo The Name is $NAME
echo The Value is $Value

echo "Enter Username : "
read
echo "Username : $REPLY"

echo "Enter Password : "
read
echo "Password : $REPLY"

echo $0 $1 $2 $3

args=("$@")

echo ${args[1]} ${args[2]}

